/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as VetsRouteImport } from './routes/vets'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReportRouteImport } from './routes/report'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseListingsListingIdRouteImport } from './routes/browse.listings.$listingId'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsRoute = VetsRouteImport.update({
  id: '/vets',
  path: '/vets',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseListingsListingIdRoute = BrowseListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => BrowseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/vets': typeof VetsRoute
  '/you': typeof YouRoute
  '/browse/listings/$listingId': typeof BrowseListingsListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/vets': typeof VetsRoute
  '/you': typeof YouRoute
  '/browse/listings/$listingId': typeof BrowseListingsListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/vets': typeof VetsRoute
  '/you': typeof YouRoute
  '/browse/listings/$listingId': typeof BrowseListingsListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/report'
    | '/saved'
    | '/vets'
    | '/you'
    | '/browse/listings/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/report'
    | '/saved'
    | '/vets'
    | '/you'
    | '/browse/listings/$listingId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/report'
    | '/saved'
    | '/vets'
    | '/you'
    | '/browse/listings/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRouteWithChildren
  ReportRoute: typeof ReportRoute
  SavedRoute: typeof SavedRoute
  VetsRoute: typeof VetsRoute
  YouRoute: typeof YouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets': {
      id: '/vets'
      path: '/vets'
      fullPath: '/vets'
      preLoaderRoute: typeof VetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/listings/$listingId': {
      id: '/browse/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/browse/listings/$listingId'
      preLoaderRoute: typeof BrowseListingsListingIdRouteImport
      parentRoute: typeof BrowseRoute
    }
  }
}

interface BrowseRouteChildren {
  BrowseListingsListingIdRoute: typeof BrowseListingsListingIdRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseListingsListingIdRoute: BrowseListingsListingIdRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRouteWithChildren,
  ReportRoute: ReportRoute,
  SavedRoute: SavedRoute,
  VetsRoute: VetsRoute,
  YouRoute: YouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router/index.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
